apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: descheduler
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra

  sources:
    - repoURL: https://kubernetes-sigs.github.io/descheduler/
      chart: descheduler
      targetRevision: 0.35.1
      helm:
        releaseName: descheduler
        valueFiles:
          - $values/kubernetes/components/descheduler/values.yaml

    - repoURL: git@github.com:arunanshub/devops.git
      targetRevision: master
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: descheduler

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
