apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - rbac.yaml
  - cronjob.yaml
  - sealedsecret-velero-r2.yaml

images:
  - name: alpine/k8s
    newTag: "1.37.1@sha256:a466f1230db238e7e534c633619b4c4c2fa5fded43c74bd7600e17545929ae98"
