apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-r2-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgApBDQsRR5FjlvoUYVwihmJQRw55Aq7fShekBBBYOLeTT3YPaOan5vETbcQfi2H2MUoEyoCZx0AaA9uAw2/LVAWxiLY0EgGqR66m2MkSAFKIN5LSIeeLO8s+IGW1VyI+PHrR0tyKpPECOMDYoYPxMFQ8Ls3uWgijW86tKn6/oHh90RRqb0aYpkU67z0ahUqH5Shx1tCx8MwHXjy12v/ITIFSbNoOfOLwNW76oHrXSG1YbC5osqIKWL7dH7UAec7p4heCgLnxYAMKLyEp4ZZD1o0ynGdohJ7BbmDmKOdzksDEA5D7JHeTVZ4J6Ufl9SgbNsWF1hC3fL9glCIJtfhT0aGYOeMWMhIgsSLjWAIHTlrFSzp3p8Mkqa4mRevuUbP6hbEjpzXMX4NJfgoszIyHsPYwB20ZaONWg2JaebTju/TbGN6UsZg1/0b2ON/sfxcsKDdFtyXe5nCLkJ97CIAkiFfLgDPFRkqbml3PBa/4F7zGYQHGXbo1JAPSJX6QCYgR1XShHLPOnD4pHVIk6xr9M4qFFZTHIyCxz75SIgTj/gmlUODcYfm5pFxXRDoCgbB6YYNQ8rbc6UukxVd1ryWDiVuCQK+vwJkQQk6OUTyqUTAS5+X/r2pHT4PnHc77u3ZS6YXyYQk4pzdNJVeYDyYC2uOgZ7S9v87GqoHUd0gAaS+EamFuyg+iDhZ22sxWQM2gWcKs9lSUGntfvG6CjjBMujI4T15ut1V8AddZm2oNuMEonDEuXxEaegoR6Ol15T9h1BdHE8OzDbyhGMaC+rhm/H7ASj5zb/ukaadFreVXwR5wQUksOEdm3a6FYi11NISMlUa0coC6nrh+u1rhTKC7exI8n82U4pgoh3ycyzLoJA08gKF4suOoi6DjzDHcgVlSuK09Fs=
  template:
    metadata:
      name: velero-r2-credentials
      namespace: velero
