apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo-vpa
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: monitoring

  source:
    repoURL: git@github.com:arunanshub/devops.git
    targetRevision: master
    path: kubernetes/components/tempo-vpa/resources

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
