apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - scaledobject.yaml
  - vpa.yaml
  - pdb.yaml
  - vmservicescrape.yaml
  - middleware.yaml
  - purge-cache-job.yaml
  - cf-cache-purge.sealedsecret.yaml

images:
  - name: arunanshu-dev
    newName: ghcr.io/arunanshub/arunanshu.dev
    newTag: 20260825220031-b090be0
