apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - scaledobject.yaml
  - vpa.yaml
  - pdb.yaml
  - vmservicescrape.yaml
  - middleware.yaml
  - purge-cache-job.yaml
  - cf-cache-purge.sealedsecret.yaml

images:
  - name: arunanshu-dev
    newName: ghcr.io/arunanshub/arunanshu.dev
    newTag: 20261007084518-481ff00
  - name: curlimages/curl
    newTag: "8.22.0@sha256:58adaa4e8dca9c988bae2aba4ab3434a0bb2da16bbe3f92dec39ec7785166777"
