apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: arunanshu-dev
  namespace: arunanshu-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: arunanshu-dev
  minReplicaCount: 1
  maxReplicaCount: 5
  pollingInterval: 30
  cooldownPeriod: 120
  fallback:
    failureThreshold: 3
    replicas: 1
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://vmsingle-victoria-metrics-k8s-stack.monitoring.svc.cluster.local:8428
        metricName: arunanshu_dev_rps_per_replica
        query: |
          sum(rate(traefik_router_requests_total{router=~"httproute-arunanshu-dev.*"}[2m]))
          / max(kube_deployment_status_replicas_available{deployment="arunanshu-dev",namespace="arunanshu-dev"})
        threshold: "50"
