apiVersion: v1
kind: Service
metadata:
  name: arunanshu-dev
  namespace: arunanshu-dev
spec:
  type: ClusterIP
  selector:
    app: arunanshu-dev
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
