apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - appproject.yaml
  - kube-prometheus-stack/grafana-admin.sealedsecret.yaml
  - kube-prometheus-stack/application.yaml
