apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-scaling
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: platform

  source:
    repoURL: git@github.com:arunanshub/devops.git
    targetRevision: master
    path: kubernetes/components/traefik-scaling/resources

  destination:
    server: https://kubernetes.default.svc
    namespace: traefik

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
