apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k3s-upgrade-plans
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: infra

  source:
    repoURL: git@github.com:arunanshub/devops.git
    targetRevision: master
    path: kubernetes/components/system-upgrade-plans/plans

  destination:
    server: https://kubernetes.default.svc
    namespace: system-upgrade

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
