apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - vpa-sealed-secrets.yaml
  - vpa-hubble-relay.yaml
  - vpa-hubble-ui.yaml
  - vpa-cilium-operator.yaml
  - vpa-cilium.yaml
