apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: sealed-secrets-controller
  namespace: kube-system
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sealed-secrets-controller
  updatePolicy:
    updateMode: InPlaceOrRecreate
    minReplicas: 1
  resourcePolicy:
    containerPolicies:
      - containerName: controller
        controlledValues: RequestsOnly
        minAllowed:
          cpu: 5m
          memory: 16Mi
        maxAllowed:
          cpu: 200m
          memory: 256Mi
