apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - appproject.yaml
  - kube-prometheus-stack/application.yaml
  - kube-prometheus-stack-secrets/application.yaml
  - tempo/application.yaml
  - grafana-route/application.yaml
  - prometheus-route/application.yaml
  - backup-alerts/application.yaml
  - backup-dashboard/application.yaml
  - network-alerts/application.yaml
