TF_VAR_hcloud_token: ENC[AES256_GCM,data:e0lsTtJGrEedVSPweEV78wemUHxHKN/tMp+GrgVl/iHGgYV6C3NpwU3I9KtVa+dpz9g3OlqulwxMOZSc7Ts2OQ==,iv:YqoJO+rXCi5QdghBzaI2iEQac+UnlO1T07m7plhBwOg=,tag:bpoQAPBqwIYwLKyIsuBrmQ==,type:str]
TF_VAR_state_passphrase: ENC[AES256_GCM,data:7r7NJdH2C7V9uk3tyhCNDZ+YWjPJZ1XPWn6CcdCeB5txzwWsPUJlEzxOAk0=,iv:QRq15PtzRowyf/KKVOVSGa5qnbPMp9veDsmwXMLIDhQ=,tag:xLjq7uVR3zgQoWeGPAz+Lw==,type:str]
TF_VAR_home_ip: ENC[AES256_GCM,data:Up5a6qtrLgs7l+GbVhx/DqR7PSnuygdrhS5IQdH9oOEUbLGXYtP5,iv:ZPmDWT122v8cZjwh6iQxawtjZlY5xr12ftP4pFPzsSA=,tag:FdsNKFAuQmFtshp/IT3b0w==,type:str]
sops:
    age:
        - recipient: age1jxpg752mg83glh63ud3uuesd0829r5vaannpn449yszx63zxc9cqz35qu7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZT1phZVdkT2ErWVRwVllZ
            VzNldWJLSWQxT0piKzZ2cHBqaW1IUE9SQjAwCi9NdUZzd2Z4OVVzNWZhd1FlV2dZ
            VTNwOWwwTkRlV2dZRkxoN1VHQkF0dUUKLS0tIFJUblFRYWVVVVp5Q2FFOGN2SXlU
            Y1U5bzhkc0lIOHN0TXlsL3plQkd1ejgKTdi00ljQpQ+q28sINSLOAmqtlwLtOBjp
            ZQ3dQ/hiwpj3GT1HUFZWFkSZ3N/Tjs/9r/vdLcDUJflQMFEFbCpGlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T18:23:50Z"
    mac: ENC[AES256_GCM,data:V1ct2Jz4yyZpEygbGLxqY9byZ4y/3V7q5WKhUUdTQpwPLN8/CQQvELFqxQZmxCROnFtszpJYifnoq6thrklwFrKjh7w31MbKGcg3CNvx81e+7596uVQYNfmWA5LftkLgCtNjFeOTURcbJMfNJmXYKk2oBOBvWPUx+sL/3sXJftY=,iv:4JkMuLFBwcNl75U3fuvqHMj/RrztTsSvg1nE03J7z/M=,tag:5cEOroeS43LKSQ0xYXXZyQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
