TF_VAR_hcloud_token: ENC[AES256_GCM,data:e0lsTtJGrEedVSPweEV78wemUHxHKN/tMp+GrgVl/iHGgYV6C3NpwU3I9KtVa+dpz9g3OlqulwxMOZSc7Ts2OQ==,iv:YqoJO+rXCi5QdghBzaI2iEQac+UnlO1T07m7plhBwOg=,tag:bpoQAPBqwIYwLKyIsuBrmQ==,type:str]
TF_VAR_state_passphrase: ENC[AES256_GCM,data:ND/xPCnyGHXnl+40VF6m5S8psCmgRnp8BA==,iv:L7iml+1vBDgdK+9Z2rlW7c28KnFjNIK5e4vnJgK4qm4=,tag:NU5cpJxLJIvYVd8uX3tHFA==,type:str]
sops:
    age:
        - recipient: age1jxpg752mg83glh63ud3uuesd0829r5vaannpn449yszx63zxc9cqz35qu7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZT1phZVdkT2ErWVRwVllZ
            VzNldWJLSWQxT0piKzZ2cHBqaW1IUE9SQjAwCi9NdUZzd2Z4OVVzNWZhd1FlV2dZ
            VTNwOWwwTkRlV2dZRkxoN1VHQkF0dUUKLS0tIFJUblFRYWVVVVp5Q2FFOGN2SXlU
            Y1U5bzhkc0lIOHN0TXlsL3plQkd1ejgKTdi00ljQpQ+q28sINSLOAmqtlwLtOBjp
            ZQ3dQ/hiwpj3GT1HUFZWFkSZ3N/Tjs/9r/vdLcDUJflQMFEFbCpGlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T13:19:45Z"
    mac: ENC[AES256_GCM,data:CunkYv7PBrOo4GTrOUuDAMrWsS6QCgM1e8DWMT5AXY+lBVhT2iebpt7K420829j27kAyq4NeislGn7kbBxGXXbFkpnsrTm9FHC64WuZPW7+XIi6V23vlkJ3GQhE+mNtm4tKwmBE+0TIBRtH8KLXSBz0bTsKkL7jglgs0x6DIPMs=,iv:rtdXUznbQCQoqFySp+lEkd0Cg8MChsYQC5lzKFRQQZ8=,tag:ql7o/RB8jckWbyv0FA5lSw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
