apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cloudflared
  updatePolicy:
    updateMode: InPlaceOrRecreate
  resourcePolicy:
    containerPolicies:
      - containerName: cloudflared
        minAllowed:
          cpu: 5m
          memory: 20Mi
        maxAllowed:
          cpu: 200m
          memory: 128Mi
