# kubernetes/base/infra/appproject.yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  description: Core infrastructure components

  sourceRepos:
    - git@github.com:arunanshub/devops.git
    - https://argoproj.github.io/argo-helm
    - https://bitnami-labs.github.io/sealed-secrets
    - https://kubereboot.github.io/charts
    - https://github.com/rancher/system-upgrade-controller
    - https://charts.hetzner.cloud
    - https://helm.cilium.io/
    - https://charts.jetstack.io
    - https://charts.fairwinds.com/stable
    - https://traefik.github.io/charts
    - https://kedacore.github.io/charts

  destinations:
    - server: https://kubernetes.default.svc
      namespace: argocd
    - server: https://kubernetes.default.svc
      namespace: kube-system
    - server: https://kubernetes.default.svc
      namespace: system-upgrade
    - server: https://kubernetes.default.svc
      namespace: cilium-secrets
    - server: https://kubernetes.default.svc
      namespace: cert-manager
    - server: https://kubernetes.default.svc
      namespace: vpa
    - server: https://kubernetes.default.svc
      namespace: traefik
    - server: https://kubernetes.default.svc
      namespace: keda
    - server: https://kubernetes.default.svc
      namespace: cloudflared

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
