# kubernetes/base/infra/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - appproject.yaml
  - argocd/application.yaml
  - sealed-secrets/application.yaml
  - system-upgrade-controller/application.yaml
  - system-upgrade-controller/plans-application.yaml
  - kured/application.yaml
  - hcloud-secret/application.yaml
  - gateway-api-crds/application.yaml
  - cilium/application.yaml
  - hcloud-ccm/application.yaml
  - hcloud-csi/application.yaml
  - cert-manager/application.yaml
