apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - appproject.yaml
  - argocd/application.yaml
  - gateway-api-crds/application.yaml
  - sealed-secrets/application.yaml
  - cilium/application.yaml
  - tailscale-operator/application.yaml
