apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - vpa-coredns.yaml
  - vpa-metrics-server.yaml
  - vpa-local-path-provisioner.yaml
  - vpa-hcloud-ccm.yaml
  - vpa-hcloud-csi-controller.yaml
  - vpa-hcloud-csi-node.yaml
  - vpa-kured.yaml
