apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: hcloud-csi-controller
  namespace: kube-system
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hcloud-csi-controller
  updatePolicy:
    updateMode: Off
  resourcePolicy:
    containerPolicies:
      - containerName: "*"
        controlledValues: RequestsOnly
        minAllowed:
          cpu: 5m
          memory: 16Mi
        maxAllowed:
          cpu: 500m
          memory: 256Mi
