apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-upgrade-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra

  source:
    repoURL: https://github.com/rancher/system-upgrade-controller
    targetRevision: v0.19.2
    path: .

  destination:
    server: https://kubernetes.default.svc
    namespace: system-upgrade

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
