apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: keda-operator
  namespace: keda
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: keda-operator
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: keda-operator-metrics-apiserver
  namespace: keda
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: keda-operator-metrics-apiserver
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: keda-admission-webhooks
  namespace: keda
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: keda-admission-webhooks
