apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hcloud
  namespace: kube-system
spec:
  encryptedData:
    network: AgDD77tgamJi8q0hA0iuOP0t6fWz8T3Lcu9vLMqGmxh8/rNqq+tOS3l/QU1/9iRJvWWjZZ2jx1IBqWENsaPQOOrfAa1FtQPd8G7OFsYTBsX7744F08KAOA9XGjg23grtaCpBvRBFb4vwc85wLQaVLGi0xiBUJzT9K1dKlFrsUJn0iXOxw5QnXzgN7CSTvexyUpKmDBPoq/sezRr5VmOXVhLTi+H/q/ddyV2pvWzgvVkZ4ta/evjnXrZWFZ8SRTx6NaHWvABRZDW/RsT8wmzkhS645h0uL8AMLxjACX1w6GiFD/DBGaOHHRsk3cnMA1iOlUFxKF48H4uiJfSoZxnVCF1UKGT/dXE5pKEz0gfGasLvs0iPyZ0mA8TpU4CWcebyEUcrEKNDsYgCGmC541doonYplmai2Im+g8+JJFEZVZW0p6jrDTq69BqWqlCUJmT8pBupPJdJWx5R4Uliu9/dR3giB3nZENLx1xXt5edsZLZrtDmPwVjCAWKk06hKOTcz8VKPktxtqVNRq7ATIroKaLWOjqdNh1L9IuKM30DMGHjyR/9Q72LLj77lD79wBgOcBBoM14rLQQM0KjKr7TaIU4EhKporxxfv2FuumepIlguidstpjQ1xTPoxXVolw6Y2rHohOREdETZ1bndXmrMhGF5f3C5uoSxhydrOzuNIn2fYCey7yvCmeYGecoQ7DccHAuIEtJI/8i8B3Cgfc8AkAjc8ZTOw
    token: AgBycvOmt58m3WqJQqjN4lQq/8Oq/hCj1IKvVpxH564/JSv6yK22LocBL+jc03NsyQpBn3Jm+b0NY3aCS3Rwq7eoWzzCpVSCcdNek/SZOp9cMd6rLvw1qfJfapSAZXAGD4LD2/UOFp75ecVSCBspnv3msMBhanA2F6W+SBx3QRbS0fgnlqdj8ksv0f8rEjEV0+oQ/qPmqiQCF7GjFBRTY6Q01ICeQ56OgPsEXL8o5E13akgj7ecSscoGH8mTj2yUyzlkzZgGOIpQlzZONWP+9PRT4g9H7twgRXA0/l8fA8+2XDXbN6+5RgsePfFPThIpdzd7xVxNkLYFVgGO/MqVi2Wq2ODh17GYRBPHvRzPZMjzFrXwCRvHWK5siHST92XcxS83APHxr28IPXhJ1VONogNXUcvE/rLUFY/5t+S5GggeJm8SwLRsB5pfGkiuD3RsSLt+q+tm6a8gFGK+ZN1/QgVHqs8zjGWdB4Ciwbh/OdwW4nMgXWoIfn4s2pQ6zpaUJQGaxgDrd+J7opcpVR1FUpZsVt6la9hcD2ElcJxuB6hNOcXKq6UG5zizJU3s593HNj9eveDd3Z+cf2vjzvIHWeF3b0MNFx0vR5RJcBeMzGwrUX3NEezmChfUn98b66B50W/MYtvpNB9UT4F/8HSWxYvzt7AOZwMDtz/sN2VUOX5lU7CsSAfN0TuZGSyKGDsOf6mmrppEH45+GLHt9Bd0tR1iuhxDfyxBeQirmtpBhriN+ZzbbNiGhcWXvbAaqtoa34k8Rk+O85/tqQY3WkKY2wYk
  template:
    metadata:
      name: hcloud
      namespace: kube-system
    type: Opaque
