apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hcloud
  namespace: kube-system
spec:
  encryptedData:
    network: AgAb9YD1/c+jWBzkXJjy0i/xyVLTBMV1Hf6aCTd7ZcZ33oz4TcA4MS50hpni6FelffRDFH8JE4HKggq7l+M8DR5TAgtE9FUocSJFDD7nmOhZINHboPjaRFkF7577zDWfbrvUXty3jPa8t+BLAuI3w6BISVJU0iIzXaSgZpLrmU4m/D7dacjbd4qoeUpsg+OnoxgjoietnERxiHKT6HdfP+m1Z+vcylLM2nsEumByXaN2qWRNHf9ig6WhtfxdoqucxVscYaltVDStCIND1pMwSN9Orv1bDXBPra0xvs2dT2vdQNO7f3IR5uW/wuWUO8ixtlS/ALAALOZsEd02Y/mxd7RZgtNJxGkhjxn4StwOaIt2aJ6weIXyGKq5YiPdHMvh/pCRf81l51+famWBe0uYUkytHkT4KJzoZTWn95t3nJg5+YiAukZBpRPTFWbxGiH5D/0gYUWUTjLSh+1+KFXGlOLQN8uwA+cgi8qJArQNWWgPUWhzznD/KGQhomKIE/WdxhgSYZm8TyNgtYGqG9kXZTVFadfA8+mNqCdgNYWapAJUvx5mgixUUVb/xe7I391E0+bccXRxdRccbP5KKNpyWIihf7VcHiFljj5qhQesY9JUmOIBOwHsHUhiEf3SlzbNnNdgOEiiUQyoRr7l/N7k2PAW+3TD8rNbGKlEt9b7te5eBfYEA5fUIzN01gZmUaJVeBRVlXTyg1Bk0crMq7ghYmUAiCkS
    token: AgBfXMVjA7woJWR03DgfA0+F9QB+oHPTBRKPMgx7zWY2/KhkcJoqXgziMo+aCE1ca2b7+Iwqtb4x8gq8+C2ALiiDBDkykS8OZ1UPFQbmkX8BLMIDp0YkkQ3fXTSwcSFLX239uoFx86tmvwS1s76vhrPLCHgKYJtzLtZcQ0Sg7nfxugISAWX83xySStgkZZHYAtqsPcOF1LUbrLeB0jThHm0kbc33fdzxr2fqFFqnGV9/izkwHhvjmdfP+osANukjb9RO4N3SGJxox50ASc1xFpiRrldqQgpwV1TO45C8DbWklppHGkjR/0T1ooYP27mkxq+xG70Tbik12olTCatwXh4hiF6qVJuye8zK0oGnYeWhHloek7EssqBJBJ3Mu9nhHayigTSlNVKiiLOEQs6iWfkRj2l2Jsld/Q9YovOjf6dMrSR0kmmLSXBtLMjuqa+iVXFC/G0UHlgAmc1+5rmIoMmeKDlinyf6J/dz39TCE7VUYne7xmn29mD9HIQjiq2wyJH8JgkiB61NsBZd2FK8B5tj53DBTO7e/q1aLdtr49lra8KxlZQBBGxebyAKOyaRT7TUloR6CHshIvGybNtcOt/TlV2v6m6i5crkVgjM5JPiaDLEwW6E9dk6mgEjLV6uIM21rJwnBpsewLOzUEeTQgoTeUi7hTMFuriGwI05ALV2rb+cMpcNspGS8P6X9Omoh1l9fZuMQ3rDA3iy+U2jKaa5a2rwsT19GvRVupsPdkRpbg4jJL/P3xpH2TAlANxp0z83QIt8g+O8VT05WRHytRM7
  template:
    metadata:
      name: hcloud
      namespace: kube-system
    type: Opaque
