apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hcloud
  namespace: kube-system
spec:
  encryptedData:
    network: AgDHGpjUE3zjvUF19LrpVtR/00coYxtX3lFxgS5k+cDmQQKT+NVsu2aq0/PkRlyYMTEj9RUsibFB8y5JbpnpT4MogZQNUmm4hUAATapTBNYrkktYXxWmMhlAu6+SpFVFf4U0viSKBDXqMY0v+t+g6x4S6gRsHodAkxw+rUUSmns5BUGntDMePGNWEn4CUMR8YeKAewunDj03kBXm0yjMsMDZMwm03ar+BRTIOXmvc0JHlD/FmhC3NvoWpOOTtmUC6Z9fePsZy3xa9w/Zc/hytnvNnHA1mpDwHMumpFPbc2Em0VNRYksJmFTWwDDsSkuGeostxBBgka65mHbqvQpBDRrrUdZ5hgGgRhzpllGqNE3BT8ARlTQCfSfkHKNCPkRsBB5DiICcWarQpkSCIfVoCoxU6dOTRAfj504/qfhQc8UbQXqmBhW5X/25cXFeZCMzQ1hmeIj4ZUX6WJpABriJELxmN2Gg4VbjmbUucfKwnfXR/ebLOrBoka64E17VtPKeVSeyS+Lm7+xv3D4ijtT4XeocbzkYX7opEvGM415sgXsVB9xDJadmUgbM0bf81H40zuVR/5Wyd71OicQKzJaOTfmxYpMbO6uRinEyY5O8TErU5fDtxp0HgTJQRaX3WAAO4KnGFqXrxmrdFcc93YLiF43oxiwI891jykPoh/UjWbj/CZsFYlQ8olojB7sYp6q74OWFMNxBBGrqdfSUIQadP5SyyXWC
    token: AgDKV02Uqh0ik559Pw4gJquf2m+NC3F13+mPA0QRoUcoEIrSKqbL/R3hOhx8YKpUuTQguram5R05Vg3ga0xkSobDaVRtaAUNCnrjwU9eft+d74Rp1t1RShKe3R16XrlLCzQajbbBhttjJT2+bv6u6NixhnY7aEXXpA+b2007eBW8hTVHPrQF14OjDRXWTB5czv2aujgRdPTffnjquujGXRrBPoGTTjFF9iVVxMxn6jE2N6iWivJR0YOKP8SC2MK+79GBK65+uDiOUPwiPqP0zJnR91qrxwd6QlG/hwh026kzjL2w+1xcu2kdKHLNK41O+cmAEy3+OzLbUP3ssOfC35BVhWCrW1hNuqPTfny2nGwWLxTSrOzW/NjQvI56pxsP65NGHlwWvFMcbRp+q9CczRPHbmcuC8x3AgbS5ScB11IH2oVJpqU95bxuiXypxJpgL1ulNw9s2imdc+/qe/pYzpvU25zlMlxq75ojYH96BconqnXncI4usTRh39+7kF2uZ4tNrrEQNLlYoTp3nTlXDNaPu/iI/4Zb+ZGkfq84c1jkQRj73MoZmXk3ccbhmwJIuQCb82CYsg6M6LRI0X8ifQj5vW5pLtrEh+qgAWF78XHotxYiLZx0sulSNE+Go2Aw6c2ij9sC9+OKKoN6uecSe2B0rmXYBiylA0POrFeyZt+aGQEh1fkxVQE6FLun19/b0WNyXb0yTuGu4cYH++CJLdigTrhyzPNCqmrTYI9HsPRuF/Prk1y9LQoY2p9OP4WlAsDRVzAxiK+EhmEWw/X+h+8Q
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: hcloud
      namespace: kube-system
    type: Opaque
