#!/bin/bash
# shellcheck disable=SC1083,SC2034,SC2154,SC2288
set -euo pipefail

mkdir -p /etc/rancher/k3s

# Most k3s config is generated by Tofu via yamlencode().
cat > /etc/rancher/k3s/config.yaml << 'K3SCFG'
${k3s_config}
K3SCFG

%{ if is_control_plane ~}
# Public IPv6 is assigned during server creation, so derive it on first boot
# and replace the marker rendered by Tofu in the tls-san list.
public_ipv6="$(
  ip -6 addr show scope global dev eth0 |
    awk '/inet6/ { sub("/.*", "", $2); print $2; exit }'
)"

sed -i "s|${node_public_ipv6_san_marker}|$${public_ipv6}|g" /etc/rancher/k3s/config.yaml
%{ endif ~}

%{ if role == "worker" ~}
curl -sfL https://get.k3s.io \
  | INSTALL_K3S_VERSION='${k3s_version}' sh -s - agent
%{ else ~}
curl -sfL https://get.k3s.io \
  | INSTALL_K3S_VERSION='${k3s_version}' sh -
%{ endif ~}

%{ if is_bootstrap ~}
# Bootstrap node only: wait until the API server is reachable.
# Joining nodes will retry their connection to the LB naturally — no wait needed.
until k3s kubectl get nodes &>/dev/null 2>&1; do
  echo "waiting for API server..."
  sleep 5
done
%{ endif ~}
