apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cronjob.yaml
  - sealedsecret-etcd-s3.yaml

images:
  - name: amazon/aws-cli
    newTag: "2.37.12@sha256:4295c1f8da478a3aaa1e015b2d4b3772ae9cdd104ce891e4008efb9592d3ce82"
