apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../components/argocd-app-controller-vpa
  - ../../components/cainjector-vpa
  - ../../components/traefik-scaling
  - ../../components/tempo-vpa
