apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../components/argocd-app-controller-vpa
  - ../../components/cainjector-vpa
  - ../../components/traefik-scaling
  - ../../components/tempo-vpa
  - ../../components/traefik-route
  - ../../components/hubble-route
  - ../../components/hcloud-ccm
  - ../../components/hcloud-csi
  - ../../components/hcloud-secret
  - ../../components/hcloud-luks-key
  - ../../components/cloudflared
  - ../../components/kured
  - ../../components/system-upgrade-controller
  - ../../components/system-upgrade-plans
  - ../../components/argocd-route
  - ../../components/etcd-snapshot-health
  - ../../components/velero-restore-drill
