apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../base/apps

components:
  - ../../components/argocd-app-controller-vpa
  - ../../components/traefik-scaling
  - ../../components/monitoring-vpa
  - ../../components/platform-misc-vpa
  - ../../components/kube-system-infra-vpa
  - ../../components/kube-system-platform-vpa
  - ../../components/traefik-route
  - ../../components/hubble-route
  - ../../components/hcloud-ccm
  - ../../components/hcloud-csi
  - ../../components/hcloud-secret
  - ../../components/hcloud-luks-key
  - ../../components/cloudflared
  - ../../components/kured
  - ../../components/system-upgrade-controller
  - ../../components/system-upgrade-plans
  - ../../components/argocd-route
  - ../../components/etcd-snapshot-health
  - ../../components/velero-restore-drill
  - ../../components/network-policies
  - ../../components/headlamp-route
  - ../../components/headlamp-vpa
