apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform

  sources:
    - repoURL: https://kedacore.github.io/charts
      chart: keda
      targetRevision: 2.20.0
      helm:
        releaseName: keda
        valueFiles:
          - $values/kubernetes/base/platform/keda/values.yaml

    - repoURL: git@github.com:arunanshub/devops.git
      targetRevision: master
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: keda

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
