apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arunanshu-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: apps

  source:
    repoURL: git@github.com:arunanshub/devops.git
    targetRevision: HEAD
    path: kubernetes/base/apps/arunanshu-dev/resources

  destination:
    server: https://kubernetes.default.svc
    namespace: arunanshu-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
