apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hcloud-luks-key
  namespace: kube-system
spec:
  encryptedData:
    encryption-passphrase: AgCvPvL5dE702xrD/lh8PSVi6dHm6mdWuhbbIQvsl2kd4toenBXA8uU3IlCDfpizSpKiwlJ9i1isyhCqv53BoEY58VOVVsfkgjA8eSfespdOghLc9kh+fXcEsvwbzRhNSIDRgFpbLztZp0L8Hn1zUEfbOcuIKj2XsqF6m46vh0kCVD8WhL8Up4Vxp8WhyYoZtSFHaJBBgyBm0h2rF0VpUWzOVDAMitimj2UUWMO/O6YV5Fyjr6qS4RiwaeyQ/IWJay8QR4Nc3FbMzfmemC++0LpMWxjCTdlj2U3QZLzSqecY7kdtp4a11rp9Eb9me0sCK+yR+LH3o/ymOMNYAO2DnCd5Q9TzG7WDGmUDYqPW4BL2VRdlr+BhLdMFArooFsKFKf9WBIz44e4F7jkSUOe1u79CIzyzPovabJn5VpiFaA2vhQKBNaNVzEnBuxD1bLlM5jHklUl/x1qG5Er/vywn9dlNsRdOu9PPB2w+vvapxysaNzsl0M1KP2CEaGXwvzf+ou3djhQzbGlubVND01JSI3ti4ftGEKmXAn3IkRxUk0Ewu48brUgd+384FEogOZz2ndFiam/TftgaEyBuVBliyPWyw4cuDsdvCaLtpfjELCNPeCe+sBvHNgIxiLnBAq1BY5pH36wWaZQCxQtiJMhn+t717PU+OKqt61ubg6CSmEjLB1IdzG+r3cCxI4nwhgZ7u4nVYNcbPNXjLUmeABnta5Q8370snRM8ishd5gtd0VqH3hvxErF3ODH86KBF/w==
  template:
    metadata:
      name: hcloud-luks-key
      namespace: kube-system
