apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-misc-vpa
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform

  source:
    repoURL: git@github.com:arunanshub/devops.git
    targetRevision: master
    path: kubernetes/components/platform-misc-vpa/resources

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
