fullnameOverride: kube-prometheus-stack

grafana:
  enabled: true
  admin:
    existingSecret: grafana-admin
    userKey: admin-user
    passwordKey: admin-password

  # persist Grafana data in the hetzner volume instead of emptyDir to persist
  # data across pod restarts
  persistence:
    enabled: true
    storageClassName: hcloud-volumes
    accessModes: ["ReadWriteOnce"]
    size: 10Gi

  ingress:
    enabled: false

prometheus:
  ingress:
    enabled: false

  prometheusSpec:
    retention: 7d
    retentionSize: 6GiB
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    # store in the hetzner volume instead of emptyDir to persist data across pod
    # restarts
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: hcloud-volumes
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

alertmanager:
  ingress:
    enabled: false

  enabled: true
  alertmanagerSpec:
    retention: 120h
    # Mount the SealedSecret into the Alertmanager pod
    secrets:
      - alertmanager-smtp
    # store in the hetzner volume instead of emptyDir to persist data across pod
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: hcloud-volumes
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

  config:
    global:
      resolve_timeout: 5m
      smtp_smarthost: "smtp.resend.com:587"
      smtp_from: "onboarding@resend.dev"
      smtp_auth_username: "resend"
      # File path is /etc/alertmanager/secrets/<secret-name>/<key>
      smtp_auth_password_file: /etc/alertmanager/secrets/alertmanager-smtp/password
      smtp_require_tls: true

    route:
      group_by: ["alertname", "namespace"]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: "email"
      routes:
        - matchers:
            - alertname = "Watchdog"
          receiver: "null"

    receivers:
      - name: "null"
      - name: "email"
        email_configs:
          - to: "mydellpc07@gmail.com" # ← your actual email
            send_resolved: true

# embedded etcd runs inside the k3s server process, not as a visible static pod like kubeadm
kubeEtcd:
  enabled: false

# disable these since we run k3s which doesn't have these components
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false

defaultRules:
  rules:
    kubeControllerManager: false
    kubeSchedulerAlerting: false
    kubeSchedulerRecording: false
    kubeProxy: false
    etcd: false
