apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: cert-manager-cainjector
  namespace: cert-manager
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cert-manager-cainjector
  updatePolicy:
    updateMode: InPlaceOrRecreate
    minReplicas: 1
  resourcePolicy:
    containerPolicies:
      - containerName: cert-manager-cainjector
        controlledValues: RequestsOnly
        minAllowed:
          cpu: 10m
          memory: 64Mi
        maxAllowed:
          cpu: 1
          memory: 128Mi
