ingressRoute:
  dashboard:
    enabled: true

providers:
  kubernetesGateway:
    enabled: true

gateway:
  listeners:
    web:
      namespacePolicy:
        from: All

service:
  spec:
    type: ClusterIP

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
