apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: compress
  namespace: monitoring
spec:
  compress:
    encodings:
      - zstd
      - br
      - gzip
    includedContentTypes:
      - text/html
      - text/plain
      - application/json
      - application/javascript
      - text/javascript
      - text/css
