apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: etcd-snapshot-health
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra

  source:
    repoURL: git@github.com:arunanshub/devops.git
    targetRevision: master
    path: kubernetes/components/etcd-snapshot-health/resources

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
