apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - vpa-grafana.yaml
  - vpa-tempo.yaml
  - vpa-vmsingle.yaml
  - vpa-vmalert.yaml
  - vpa-vmalertmanager.yaml
  - vpa-vm-operator.yaml
  - vpa-kube-state-metrics.yaml
