apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: argocd-application-controller
  namespace: argocd
spec:
  maxUnavailable: 25%
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-application-controller
