apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  description: Cloud-agnostic service platform — ingress, TLS, autoscaling, external access

  sourceRepos:
    - git@github.com:arunanshub/devops.git
    - https://traefik.github.io/charts
    - https://charts.jetstack.io
    - https://charts.fairwinds.com/stable
    - https://kedacore.github.io/charts

  destinations:
    - server: https://kubernetes.default.svc
      namespace: traefik
    - server: https://kubernetes.default.svc
      namespace: cert-manager
    - server: https://kubernetes.default.svc
      namespace: vpa
    - server: https://kubernetes.default.svc
      namespace: keda
    - server: https://kubernetes.default.svc
      namespace: cloudflared

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
