apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-smtp
  namespace: monitoring
  annotations:
    # must exist before the Alertmanager deployment is created
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    password: AgBHiFT1lqlnpHe00TnY1+ggoD1M0D+iUwihCj1cTXyd0nUf5OMqAjiwPa1C97H1B56tVHGaPbnVII7us/M6OY0MdvwWoCq1tCb4xVdoaZOCppQcsxWjmU9bOHUZ6LOA50sbeVtuYDtjhbiWpi7XY1QFkIqUCZqe5hc2cCT1doJ6iPQ92WoULwHDXFqve+XbEr8rm3s9dPg8Utm+2bxJ+JhRRaqk9WCtAVDKcHEGlcV4iTCLIJRwx7WSZt94zWbOZjbiC6JsuM8IjARvBNvwOMjWKQ+Pjockc/WAmI7tWc9ZOEfuKJ2e/y2rlyR1gqAvcOuoAYDb2oIb2LaVeRFNpPDEKEwWGThVgs1iyqr2ozVWrnn85VRegW1qvCSLyLWWzNx8h8iidbvM/oZqEJTFUZoZ8k6Y3n7lgAGsHf+bds1xc8pzH+Skw9EZRB4ww3UOTZpvzuliT+1WTjYfGMY5BgLNWRA+WsyqAC4kMgzGX0mYAQiyqjkqzZ0FCv5l0v4B6Qk5LaNwpJushcVFkCvJAyMWrfuw7CKTHF7FCTjbuy1abL3mb6JCP6qPYD+vy1bICpP1V7LkwcI+XFJzHC7uCX4Fd7QhJWo+wmCOOY/ohRhQGdXJFEOxLi6VGDFu5y12ecq+hNVyNLjApIhDtRaXjKQWmx3w8Pl13r16HjclFNPUEGeJxxFZNWHEIoQv3uPx1Hf9hA8KHPXoagcZqF19oeILIlNm6v34oaIflx2PQrhvuLf7RNk=
  template:
    metadata:
      name: alertmanager-smtp
      namespace: monitoring
