fullnameOverride: kube-prometheus-stack

grafana:
  enabled: true
  admin:
    existingSecret: grafana-admin
    userKey: admin-user
    passwordKey: admin-password

  ingress:
    enabled: false

prometheus:
  ingress:
    enabled: false

  prometheusSpec:
    retention: 7d
    retentionSize: 8GiB
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false

alertmanager:
  enabled: true
  ingress:
    enabled: false

  alertmanagerSpec:
    retention: 120h

# embedded etcd runs inside the k3s server process, not as a visible static pod like kubeadm
kubeEtcd:
  enabled: false

# disable these since we run k3s which doesn't have these components
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false

defaultRules:
  rules:
    kubeControllerManager: false
    kubeSchedulerAlerting: false
    kubeSchedulerRecording: false
    kubeProxy: false
    etcd: false
