apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: monitoring

  sources:
    - repoURL: https://grafana-community.github.io/helm-charts
      chart: tempo
      targetRevision: 2.3.0
      helm:
        releaseName: tempo
        valueFiles:
          - $values/kubernetes/base/monitoring/tempo/values.yaml

    - repoURL: git@github.com:arunanshub/devops.git
      targetRevision: master
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
