apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - middleware.yaml
  - vmservicescrape.yaml
  - purge-cache-job.yaml
  - cf-cache-purge.sealedsecret.yaml

images:
  - name: libby-hbd-2026
    newName: ghcr.io/arunanshub/libby-hbd-2026.arunanshu.dev
    newTag: 20261004090052-258d868
  - name: curlimages/curl
    newTag: "8.14.1@sha256:9a1ed35addb45476afa911696297f8e115993df459278ed036182dd2cd22b67b"
