apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - middleware.yaml
  - vmservicescrape.yaml
  - purge-cache-job.yaml
  - cf-cache-purge.sealedsecret.yaml

images:
  - name: libby-hbd-2026
    newName: ghcr.io/arunanshub/libby-hbd-2026.arunanshu.dev
    newTag: 20260916011048-4e61777
