apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kured
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra

  sources:
    - repoURL: https://kubereboot.github.io/charts
      chart: kured
      targetRevision: 6.1.0
      helm:
        releaseName: kured
        valueFiles:
          - $values/kubernetes/components/kured/values.yaml

    - repoURL: git@github.com:arunanshub/devops.git
      targetRevision: master
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
